import Head from 'next/head'
import { ConnectedPeerList } from '@/components/PeerList'
import { PubsubSubscribers } from '@/components/Pubsub'
import { DirectMessages } from '@/components/DirectMessages'
import ChatContainer from '@/components/chat/ChatContainer'
import Nav from '@/components/Nav'

export default function Chat() {
  return (
    <>
      <Head>
        <title>js-libp2p Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-full">
        <Nav />
        <div className="flex flex-row">
          <div className="basis-2/12">
            <DirectMessages />
          </div>
          <div className="basis-8/12">
            <ChatContainer />
          </div>
          <div className="basis-2/12">
            <PubsubSubscribers />
            <ConnectedPeerList showShortPeerId />
          </div>
        </div>
      </main>
    </>
  )
}
