import Head from 'next/head'
import { DirectMessagesList } from '@/components/directmessages/DirectMessagesList'
import Nav from '@/components/Nav'

// Shown on mobile only
export default function DirectMessages() {
  return (
    <>
      <Head>
        <title>js-libp2p Direct Messages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <Nav />
        <div className="">
          <DirectMessagesList isMobilePage={true} />
        </div>
      </main>
    </>
  )
}
