name: rust-peer ci

on: 
  pull_request:
    paths:
      - 'rust-peer/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: '-Dwarnings' # Never tolerate warnings.
    defaults:
      run:
        working-directory: ./rust-peer
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo clippy
      - run: cargo test